language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
addons:
  apt:
    packages:
      - libopenblas-base
      - libopenblas-dev
      - liblapack-dev
      - gfortran
before_install:
  - pip install --upgrade pip
install:
  - pip install -r requirements.txt
  - python setup.py build_ext --inplace
script: "nosetests"
notifications:
  email: false
